# Generated by Django 5.2.8 on 2026-04-21 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vita', '0002_category_blog_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Check this to show at the top'),
        ),
    ]
