# Generated by Django 5.2.8 on 2026-04-21 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vita', '0003_blog_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
