# Generated by Django 5.2.8 on 2026-04-29 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vita', '0008_primarycategory_remove_blog_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='focus_keyword',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='meta_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='seo_score',
            field=models.IntegerField(default=0),
        ),
    ]
