# Generated by Django 5.2.8 on 2026-05-03 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vita', '0009_blog_focus_keyword_blog_meta_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='focus_keyword',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='meta_title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='primarycategory',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
