# Generated by Django 5.2.8 on 2026-05-03 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vita', '0010_alter_blog_focus_keyword_alter_blog_meta_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='secondarycategory',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
