# Generated by Django 5.2.8 on 2026-05-03 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vita', '0011_alter_blog_slug_alter_blog_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
    ]
