# Generated by Django 5.2.8 on 2026-05-14 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vita', '0012_alter_blog_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('category', models.CharField(choices=[('general', 'General Query'), ('bug', 'Bug / Error Report'), ('content', 'Content Feedback'), ('feature', 'Feature Request'), ('partnership', 'Partnership'), ('privacy', 'Privacy / Legal')], default='general', max_length=30)),
                ('calculator', models.CharField(blank=True, max_length=150)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('spam', 'Spam')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
