# Generated by Django 5.2.8 on 2026-05-14 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vita', '0013_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='ticket_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
