# Generated by Django 5.2.8 on 2026-05-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vita', '0014_contactmessage_ticket_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='ticket_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
