# Generated by Django 5.2.8 on 2026-05-14 16:45

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vita', '0016_privacypolicy'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('page_type', models.CharField(choices=[('privacy-policy', 'Privacy Policy'), ('disclaimer', 'Disclaimer'), ('terms-of-use', 'Terms of Use')], max_length=50, unique=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
