# Generated by Django 5.2.8 on 2026-05-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vita', '0017_legalpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalpage',
            name='short_description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
