# Generated by Django 5.2.8 on 2026-05-17 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vita', '0019_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blogs', to='vita.author'),
        ),
    ]
