# Generated by Django 5.2.8 on 2026-05-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vita', '0020_blog_author_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='expertise',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='author',
            name='role',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
