# Generated by Django 5.2.8 on 2026-05-18 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vita', '0021_author_expertise_author_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_blogs', to='vita.author'),
        ),
    ]
