# Generated by Django 5.2.8 on 2026-05-18 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vita', '0022_blog_reviewed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_blogs', to='vita.author'),
        ),
    ]
