# Generated by Django 5.2.8 on 2026-05-20 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vita', '0023_blog_edited_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='default.webp', upload_to='blogs/'),
        ),
    ]
