# Generated by Django 5.2.8 on 2026-05-20 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vita', '0024_alter_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='blogs/default.webp', upload_to='blogs/'),
        ),
    ]
